"""Add queue_status and queue_entry_time to User model

Revision ID: 008c2486c331
Revises: 6529a0588a75
Create Date: 2025-10-31 01:29:51.690874

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "008c2486c331"
down_revision: Union[str, None] = "6529a0588a75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("queue_status", sa.String(), nullable=True))
    op.add_column("users", sa.Column("queue_entry_time", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_users_queue_status"), "users", ["queue_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_queue_status"), table_name="users")
    op.drop_column("users", "queue_entry_time")
    op.drop_column("users", "queue_status")
    # ### end Alembic commands ###
