"""Update User schema and remove has_active_payment route

Revision ID: 1704152e8474
Revises: ea1a9403c144
Create Date: 2025-11-03 14:35:07.383344

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1704152e8474"
down_revision: Union[str, None] = "ea1a9403c144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
