"""Initial migration

Revision ID: 3d3b78623bab
Revises: 
Create Date: 2025-10-28 04:46:44.331091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3b78623bab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'medical_records', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'prescriptions', 'users', ['prescriber_id'], ['id'])
    op.create_foreign_key(None, 'prescriptions', 'users', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    # ### end Alembic commands ###
