"""Add address fields to User model

Revision ID: 6529a0588a75
Revises: 3d3b78623bab
Create Date: 2025-10-28 11:47:36.886832

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6529a0588a75"
down_revision: Union[str, None] = "3d3b78623bab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("logradouro", sa.String(), nullable=True))
    op.add_column("users", sa.Column("numero", sa.String(), nullable=True))
    op.add_column("users", sa.Column("complemento", sa.String(), nullable=True))
    op.add_column("users", sa.Column("bairro", sa.String(), nullable=True))
    op.add_column("users", sa.Column("estado", sa.String(), nullable=True))
    op.add_column("users", sa.Column("cidade", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cidade")
    op.drop_column("users", "estado")
    op.drop_column("users", "bairro")
    op.drop_column("users", "complemento")
    op.drop_column("users", "numero")
    op.drop_column("users", "logradouro")
    # ### end Alembic commands ###
