"""add_role_to_user

Revision ID: 7fa22ab23f85
Revises: bdc0c3792aa1
Create Date: 2025-11-10 11:13:26.979746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa22ab23f85'
down_revision: Union[str, None] = 'bdc0c3792aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = sa.Enum('SUPERADMIN', 'ADMIN', 'CUSTOMER', 'DOCTOR', name='role')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', role_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
