"""Add Payment model and user relationship

Revision ID: 9f20a34e0e0c
Revises: 008c2486c331
Create Date: 2025-11-03 12:40:40.419214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f20a34e0e0c'
down_revision: Union[str, None] = '008c2486c331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
