"""make_user_role_not_nullable

Revision ID: ab928d9a7291
Revises: 7fa22ab23f85
Create Date: 2025-11-10 11:14:34.938771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab928d9a7291'
down_revision: Union[str, None] = '7fa22ab23f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET role = 'CUSTOMER' WHERE role IS NULL")
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPERADMIN', 'ADMIN', 'CUSTOMER', 'DOCTOR', name='role'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPERADMIN', 'ADMIN', 'CUSTOMER', 'DOCTOR', name='role'),
               nullable=True)
    # ### end Alembic commands ###
