"""Add PIX fields to Payment model

Revision ID: bdc0c3792aa1
Revises: 1704152e8474
Create Date: 2025-11-04 10:41:07.134690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc0c3792aa1'
down_revision: Union[str, None] = '1704152e8474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('pix_transaction_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('pix_qr_code_data', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('pix_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'pix_status')
    op.drop_column('payments', 'pix_qr_code_data')
    op.drop_column('payments', 'pix_transaction_id')
    # ### end Alembic commands ###
