"""Add Payment model and user relationship

Revision ID: d70ddea16cfb
Revises: 9f20a34e0e0c
Create Date: 2025-11-03 12:48:49.541045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70ddea16cfb'
down_revision: Union[str, None] = '9f20a34e0e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
