"""Add Payment model and user relationship

Revision ID: ea1a9403c144
Revises: d70ddea16cfb
Create Date: 2025-11-03 12:52:05.336370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1a9403c144'
down_revision: Union[str, None] = 'd70ddea16cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time_db', sa.DateTime(), nullable=False),
    sa.Column('date_time', sa.String(), nullable=False),
    sa.Column('invoice', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.Column('blocked_balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date_time_db'), 'transactions', ['date_time_db'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date_time_db'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
