"""Add document fields to user model

Revision ID: f1acc189dddd
Revises: 0e289dbdea9f
Create Date: 2025-11-12 14:45:59.163338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1acc189dddd'
down_revision: Union[str, None] = '0e289dbdea9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('professional_card_document', sa.String(), nullable=True))
    op.add_column('users', sa.Column('selfie_document', sa.String(), nullable=True))
    op.add_column('users', sa.Column('proof_of_residence_document', sa.String(), nullable=True))
    op.drop_column('users', 'attached_document')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attached_document', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'proof_of_residence_document')
    op.drop_column('users', 'selfie_document')
    op.drop_column('users', 'professional_card_document')
    # ### end Alembic commands ###
