"""add_doctor_fields_to_user

Revision ID: fad5b50210e2
Revises: ab928d9a7291
Create Date: 2025-11-10 12:03:57.937904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad5b50210e2'
down_revision: Union[str, None] = 'ab928d9a7291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crm', sa.String(), nullable=True))
    op.add_column('users', sa.Column('uf_crm', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_information', sa.String(), nullable=True))
    op.add_column('users', sa.Column('attached_document', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'attached_document')
    op.drop_column('users', 'bank_information')
    op.drop_column('users', 'uf_crm')
    op.drop_column('users', 'crm')
    # ### end Alembic commands ###
